### ISSUE TITLE
[Retrospect] 2주차 회고 - 이계진

### ISSUE THREAD

**Issue by faker007** [codestates/1_shapsol_client#9]
# 이계진

### Fact (사실) : 주요 사건에서 내가 취한 행동을 객관적으로 서술한다
- 상걸님이 만들어 주신 회원 가입과, 로그인 기능을 API 엔드 포인트에 연결 했다.
- 토스트 SMS API를 가지고 문자 인증 시스템을 개발 했다.

### Feeling (느낌) : 그때 느꼈던 기분을 간략히 정리한다
- 든든한 팀원 분들이 계셔서 안도감과 다행을 느꼈다.
- 조금이라도 복잡한 로직에서는 갈 길을 잃어서, 조금은 머리가 복잡했다.

### Finding (교훈) : 사건에서 얻은 교훈을 적는다  
- 앞으로는 보다 상세하게 히스토리를 적재 하고, 과거와 미래를 적절하게 살펴 보면서 앞으로 가야 겠다고 생각 했다.

### Future action(행동) : 그래서 내가 앞으로 취할 행동을 미래형으로 적는다  
- 노션에 히스토리를 조금 더 가독성 있게 적재 할 것이다.
- 노션에 적재한 히스토리를 하루를 시작하기 전에 한 번 다시 훑어 볼 것이다.

**Comment by ghost** [comment]
ㅇㄱㅈ 이분 학생들한테 돈 70만원씩 사기치고 다닙니다.
